package ports

import (
	"time"

	"github.com/ilindan-dev/dungeon-log/internal/core/domain"
)

// Reporter defines the contract for outputting system responses and the final report.
type Reporter interface {
	// EmitOutgoing logs an event generated by the system (e.g., dead, disqualified).
	EmitOutgoing(time time.Time, eventID domain.EventID, playerID int, extra string) error

	// PrintFinalReport outputs the summarized results for all participants.
	PrintFinalReport(players []*domain.Player) error

	// EmitIncoming echoes a successfully processed player action.
	EmitIncoming(event domain.Event) error
}
