package domain

import "time"

// EventID represents the unique identifier for incoming and outgoing challenge events.
type EventID int

// Incoming events generated by the player actions.
const (
	_                   EventID = iota
	EventRegistered             // 1: Player registered
	EventEntered                // 2: Player entered the dungeon
	EventKilledMonster          // 3: Player killed a monster
	EventNextFloor              // 4: Player went to the next floor
	EventPrevFloor              // 5: Player went to the previous floor
	EventEnteredBoss            // 6: Player entered the boss's floor
	EventKilledBoss             // 7: Player killed the boss
	EventLeftDungeon            // 8: Player left the dungeon
	EventCannotContinue         // 9: Player cannot continue due to some reason
	EventRestoredHealth         // 10: Player has restored health
	EventReceivedDamage         // 11: Player received damage
)

// Outgoing events generated by the system in response to player actions.
const (
	OutEventDisqualified EventID = iota + 31 // 31: Player disqualified
	OutEventDead                             // 32: Player is dead
	OutEventInvalidMove                      // 33: Player makes an impossible move
)

// Event represents a single action or occurrence within the dungeon timeline.
type Event struct {
	// ID is the numeric identifier of the event type.
	ID EventID

	// PlayerID is the unique identifier of the participant.
	PlayerID int

	// ExtraParam holds additional contextual data, such as damage amounts,
	// health restored, or text reasons for being unable to continue.
	ExtraParam string

	// Time is the exact moment the event occurred.
	Time time.Time
}
