name: CI/CD Builder Pipeline

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  lint-and-test:
    name: Build, Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9

      - name: Run Tests
        run: make test

      - name: Build
        run: make build